sudo: required
services:
  - docker

before_install:
  - docker build -t djontung/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true djontung/react-test npm test -- --coverage

after_success:
  - docker build -t djontung/multi-client ./client
  - docker build -t djontung/multi-nginx ./nginx
  - docker build -t djontung/multi-server ./server
  - docker build -t djontung/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push djontung/multi-client
  - docker push djontung/multi-nginx 
  - docker push djontung/multi-server
  - docker push djontung/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-west-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-west-2-517530927865'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY